# Generated by Django 4.2.23 on 2025-11-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0024_metacheckreport_db_report_m_subtype_2272a8_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="EsStatusReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("state", models.CharField(default="", help_text="巡检结果状态", max_length=64)),
                ("failed_days", models.IntegerField(default=0, help_text="失败持续天数")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("domain", models.CharField(default="", max_length=255)),
                ("app", models.CharField(max_length=100, verbose_name="业务名")),
                ("dba", models.JSONField(max_length=100, verbose_name="业务所属dba")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
