# Generated by Django 4.2.23 on 2025-11-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0025_esstatusreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="EsAccountReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("state", models.CharField(default="", help_text="巡检结果状态", max_length=64)),
                ("failed_days", models.IntegerField(default=0, help_text="失败持续天数")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("domain", models.CharField(default="", max_length=255)),
                ("app", models.CharField(max_length=100, verbose_name="业务名")),
                ("dba", models.JSONField(max_length=100, verbose_name="业务所属dba")),
                ("have_admin", models.BooleanField(default=False, verbose_name="ADMIN账号")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EsDatanodeReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("state", models.CharField(default="", help_text="巡检结果状态", max_length=64)),
                ("failed_days", models.IntegerField(default=0, help_text="失败持续天数")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("domain", models.CharField(default="", max_length=255)),
                ("app", models.CharField(max_length=100, verbose_name="业务名")),
                ("dba", models.JSONField(max_length=100, verbose_name="业务所属dba")),
                ("idc_affinity_hot", models.IntegerField(default=1, verbose_name="热节点机房亲合度")),
                ("rack_affinity_hot", models.IntegerField(default=1, verbose_name="热节点机架亲合度")),
                ("idc_affinity_cold", models.IntegerField(default=1, verbose_name="冷节点机房亲合度")),
                ("rack_affinity_cold", models.IntegerField(default=1, verbose_name="冷节点机架亲合度")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EsDomainReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("state", models.CharField(default="", help_text="巡检结果状态", max_length=64)),
                ("failed_days", models.IntegerField(default=0, help_text="失败持续天数")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("domain", models.CharField(default="", max_length=255)),
                ("app", models.CharField(max_length=100, verbose_name="业务名")),
                ("dba", models.JSONField(max_length=100, verbose_name="业务所属dba")),
                (
                    "type",
                    models.CharField(
                        choices=[("dns", "dns"), ("clb", "clb"), ("polaris", "polaris"), ("clbDns", "clbDns")],
                        max_length=255,
                        verbose_name="类型",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EsMasterReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("state", models.CharField(default="", help_text="巡检结果状态", max_length=64)),
                ("failed_days", models.IntegerField(default=0, help_text="失败持续天数")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("domain", models.CharField(default="", max_length=255)),
                ("app", models.CharField(max_length=100, verbose_name="业务名")),
                ("dba", models.JSONField(max_length=100, verbose_name="业务所属dba")),
                ("master_count", models.IntegerField(default=0, verbose_name="master数量")),
                ("idc_affinity", models.IntegerField(default=1, verbose_name="机房亲合度")),
                ("rack_affinity", models.IntegerField(default=1, verbose_name="机架亲合度")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EsVersionReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("state", models.CharField(default="", help_text="巡检结果状态", max_length=64)),
                ("failed_days", models.IntegerField(default=0, help_text="失败持续天数")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("domain", models.CharField(default="", max_length=255)),
                ("app", models.CharField(max_length=100, verbose_name="业务名")),
                ("dba", models.JSONField(max_length=100, verbose_name="业务所属dba")),
                ("major_version", models.CharField(default="", max_length=100, verbose_name="主版本")),
                ("version_count", models.IntegerField(default=0, verbose_name="版本数量")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
